### ISSUE TITLE
Problem converting amount to int

### ISSUE THREAD

**Issue by Thiousi** [jordanmerrick/sck#2]
I get the following error in the example checkout page:
Notice: Object of class Field could not be converted to int in xxxxx/public_html/site/snippets/sck.php on line 25

Fixed it by replacing line 14 by:
$displayAmount = $page->amount()->int();

And 15 and 16 by:
$amount	= $page->amount()->int();

**Comment by jordanmerrick** [comment]
What version of PHP are you running? I can't reproduce the error and making the changes results in the error "Call to a member function int() on a non-object".
